name: CI devops 2023
on:
  #to begin you want to launch this job in main and develop
  push:
    branches:
     - main
  pull_request:

jobs:
  test-backend: 
   runs-on: ubuntu-22.04
   steps:
    #checkout your github code using actions/checkout@v3
    - uses: actions/checkout@v3

    #do the same with another action (actions/setup-java@v3) that enable to setup jdk 17 wesh
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: "adopt"

    #finally build your app with the latest command
    - name: Build and test with Maven
      run: mvn clean verify --file api/pom.xml
